Repository marso34/ytt-medicine-vending-machine, pull requests merged in 2024-11, with the labels that each got.

#69 [FIX] HTTP 200 ok 일때도 ResponseDto로 반환하도록 수정
  BE/ytt/src/main/java/com/example/ytt/domain/user/controller/UserController.java
Labels: BUG 🐞

#71 [FIX] User,Auth 응답 ResponseDto로 수정
  BE/ytt/src/main/java/com/example/ytt/domain/user/auth/jwt/JWTFilter.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/auth/jwt/JWTUtil.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/auth/security/CustomLogoutFilter.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/auth/security/LoginFailHandler.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/auth/security/LoginSuccessHandler.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/controller/AuthController.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/controller/UserController.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/exception/UserExceptionType.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/service/AuthService.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/service/UserService.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SecurityConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/util/ResponseUtil.java
Labels: BUG 🐞

#73 [FEAT] 자판기 즐겨찾기 및 입고 로직 추가 : BE
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/controller/InboundController.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/domain/InboundLog.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/domain/Inventory.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/dto/InboundLogDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/dto/InboundReqDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InboundLogRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InventoryRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/service/InboundService.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/service/InventoryService.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/controller/MedicineController.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Medicine.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDetailDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/service/MedicineRegisterService.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/domain/User.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/controller/VendingMachineFindController.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/controller/VendingMachineManageController.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/domain/Favorite.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/dto/TempReqDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/repository/FavoriteRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/service/FavoriteService.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/service/VendingMachineFindService.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/service/VendingMachineManageService.java
  BE/ytt/src/test/java/com/example/ytt/domain/vendingmachine/service/VendingMachineFindServiceTest.java
Labels: FEAT ✨

#74 [FIX] 경로 문제 해결 : BE
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/controller/InboundController.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SecurityConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SwaggerConfig.java
Labels: BUG 🐞

#80 [FEAT] 주문 생성 개발 BE
  BE/ytt/src/main/java/com/example/ytt/domain/order/controller/OrderController.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/domain/Order.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/domain/OrderDetail.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/domain/OrderState.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderDetailDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderDetailReqDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderReqDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/repository/OrderDetailRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/repository/OrderRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderDetailService.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderService.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SwaggerConfig.java
  BE/ytt/src/test/java/com/example/ytt/domain/order/service/OrderServiceTest.java
Labels: FEAT ✨

#82 [FIX]: ExceptionType 변경에 따른 코드 수정
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderService.java
Labels: BUG 🐞

#86 [FEAT] 백엔드 모니터링 : BE
  BE/ytt/build.gradle
  BE/ytt/src/main/java/com/example/ytt/global/config/SecurityConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SwaggerConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/error/handler/ExceptionAdvice.java
  BE/ytt/src/main/resources/application.yml
Labels: FEAT ✨

#90 [FEAT] QueryDSL 적용 : BE
  BE/ytt/build.gradle
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InventoryRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InventoryRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InventoryRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/service/InboundService.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/service/InventoryService.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/controller/MedicineController.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/repository/MedicineRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/repository/MedicineRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/repository/MedicineRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/service/MedicineFindService.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/controller/VendingMachineFindController.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/repository/VendingMachineRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/repository/VendingMachineRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/repository/VendingMachineRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/service/VendingMachineFindService.java
  BE/ytt/src/main/java/com/example/ytt/global/config/QueryDslConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/error/code/ExceptionType.java
Labels: FEAT ✨, REFACTOR 🛠️

#93 [FEAT] 웹소켓 주문 통신 개발 : BE
  BE/ytt/build.gradle
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InventoryRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/controller/OrderController.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/controller/OrderWebSocketController.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/controller/WebSocketTestController.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/domain/Order.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/domain/OrderState.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderDetailDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderDetailReqDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderStoreResDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderVendingMachineDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/exception/OrderException.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/repository/OrderRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderService.java
  BE/ytt/src/main/java/com/example/ytt/global/config/CorsMvcConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SecurityConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/config/WebSocketConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/error/code/ExceptionType.java
  BE/ytt/src/main/resources/templates/websocket-user-test.html
  BE/ytt/src/main/resources/templates/websocket-vm-test.html
Labels: FEAT ✨

#94 [FIX] 누락된 import 추가
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InventoryRepository.java
Labels: BUG 🐞

#95 [FEAT] 자판기 관리 기능 : BE
  BE/ytt/.gitignore
  BE/ytt/build.gradle
  BE/ytt/src/main/java/com/example/ytt/domain/favorite/controller/FavoriteController.java
  BE/ytt/src/main/java/com/example/ytt/domain/favorite/domain/Favorite.java
  BE/ytt/src/main/java/com/example/ytt/domain/favorite/repository/FavoriteRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/favorite/repository/FavoriteRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/favorite/repository/FavoriteRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/favorite/service/FavoriteService.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/controller/InboundController.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/dto/InboundReqDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InboundLogRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InboundLogRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InboundLogRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/service/InboundService.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/service/InventoryService.java
  BE/ytt/src/main/java/com/example/ytt/domain/management/controller/ManagementController.java
  BE/ytt/src/main/java/com/example/ytt/domain/management/domain/Management.java
  BE/ytt/src/main/java/com/example/ytt/domain/management/repository/ManagementRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/management/repository/ManagementRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/management/repository/ManagementRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/management/service/ManagementService.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/controller/MedicineFindController.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/controller/MedicineManageController.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/service/MedicineFindService.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/domain/User.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/dto/UserDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/controller/VendingMachineFindController.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/controller/VendingMachineManageController.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/domain/VendingMachine.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/repository/VendingMachineRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/repository/VendingMachineRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/service/VendingMachineFindService.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/service/VendingMachineManageService.java
  BE/ytt/src/main/java/com/example/ytt/global/common/annotation/SwaggerApi.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SwaggerConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/error/handler/ExceptionAdvice.java
Labels: FEAT ✨, REFACTOR 🛠️

#97 [FEAT] API test 스크립트 추가 - bruno
  api-tests/auth/SignIn.bru
  api-tests/auth/SignUp.bru
  api-tests/bruno.json
  api-tests/collection.bru
  api-tests/environments/local.bru
  api-tests/environments/prod.bru
  api-tests/favorite/즐겨찾기 삭제.bru
  api-tests/favorite/즐겨찾기 조회.bru
  api-tests/favorite/즐겨찾기 추가.bru
  api-tests/inbound/입고 기록 조회.bru
  api-tests/inbound/입고.bru
  api-tests/management/관리 자판기 조회.bru
  api-tests/management/자판기 관리자 조회.bru
  api-tests/medicine/관리/약 생성.bru
  api-tests/medicine/조회/약 기본 조회.bru
  api-tests/medicine/조회/약 상세 조회.bru
  api-tests/medicine/조회/전체 약 조회.bru
  api-tests/order/주문 요청.bru
  api-tests/vending-machine/관리/자판기 생성.bru
  api-tests/vending-machine/관리/자판기 약 등록.bru
  api-tests/vending-machine/관리/자판기 운영 상태 변경.bru
  api-tests/vending-machine/조회/자판기 기본 조회.bru
  api-tests/vending-machine/조회/자판기 상세 조회.bru
  api-tests/vending-machine/조회/자판기 조회 by 약.bru
  api-tests/vending-machine/조회/전체 자판기 조회.bru
  api-tests/vending-machine/조회/특정 자판기의 전체 약 조회.bru
  api-tests/vending-machine/조회/특정 자판기의 특정 약 조회.bru
Labels: FEAT ✨

#101 [REFACTOR] 자판기에서 주문 처리를 위한 도메인 수정 : BE
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderVendingMachineDto.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SecurityConfig.java
Labels: REFACTOR 🛠️

#102 FIX: OrderDetailDto 클래스명 오타 수정 : BE
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderVendingMachineDto.java
Labels: BUG 🐞
