Repository marso34/ytt-medicine-vending-machine, pull requests merged in 2024-10, with the labels that each got.

#9 [CHORE] Spring Boot 의종성 추가 BE
  BE/ytt/.gitignore
  BE/ytt/build.gradle
  BE/ytt/src/main/resources/application-local.yml
  BE/ytt/src/main/resources/application.properties
  BE/ytt/src/main/resources/application.yml
Labels: CHORE 💡

#11 [FEAT] Swagger 설정 BE
  BE/ytt/.gitignore
  BE/ytt/src/main/java/com/example/ytt/global/config/SwaggerConfig.java
  BE/ytt/src/main/resources/application.yml
Labels: FEAT ✨

#15 [FEAT] 자판기 entity 및 repository 생성 BE
  BE/ytt/build.gradle
  BE/ytt/src/main/java/com/example/ytt/domain/model/Address.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/domain/MachineState.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/domain/VendingMachine.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/repository/VendingMachineRepository.java
  BE/ytt/src/main/java/com/example/ytt/global/util/GeometryUtil.java
  BE/ytt/src/main/resources/application-local.yml
  BE/ytt/src/main/resources/sql/h2gis.sql
  BE/ytt/src/test/java/com/example/ytt/domain/model/AddressTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/vendingmachine/domain/VendingMachineTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/vendingmachine/repository/VendingMachineRepositoryTest.java
Labels: FEAT ✨

#24 [FEAT] 유저 entity 생성, 예외처리 BE
  BE/ytt/src/main/java/com/example/ytt/domain/user/domain/User.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/dto/Role.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/exception/ExceptionAdvice.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/exception/UserException.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/exception/UserExceptionType.java
  BE/ytt/src/main/java/com/example/ytt/global/common/BaseEntity.java
  BE/ytt/src/main/java/com/example/ytt/global/error/BaseException.java
  BE/ytt/src/main/java/com/example/ytt/global/error/BaseExceptionType.java
Labels: FEAT ✨

#29 [FEAT] Swagger 간편화 및 응답 dto 통일
  BE/ytt/src/main/java/com/example/ytt/domain/user/exception/ExceptionAdvice.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/exception/UserException.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/controller/VendingMachineController.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/domain/VendingMachine.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/dto/VendingMachineDto.java
  BE/ytt/src/main/java/com/example/ytt/global/common/annotation/SwaggerApi.java
  BE/ytt/src/main/java/com/example/ytt/global/common/response/ResponseDto.java
  BE/ytt/src/main/java/com/example/ytt/global/error/BaseException.java
  BE/ytt/src/main/java/com/example/ytt/global/util/ResponseUtil.java
Labels: FEAT ✨, REFACTOR 🛠️

#43 Refactor/25 refactor 파일명 및 구조 변경 fe
  FE/app/src/main/AndroidManifest.xml
  FE/app/src/main/java/com/wonchihyeon/ytt_android/MainActivity.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/OrderDetailsActivity.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/auth/FindIdActivity.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/auth/FindPasswordActivity.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/auth/JoinActivity.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/auth/LoginActivity.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/database/AppDatabase.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/model/Medicine.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/model/Order.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/model/User.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/model/VendingMachine.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/network/ApiService.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/repository/MedicineRepository.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/repository/OrderRepository.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/repository/UserRepository.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/data/repository/VendingMachineRepository.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/view/AddressBottomSheetFragment.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/view/FavoriteFragment.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/view/HomeFragment.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/view/MyFragment.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/view/OrderListFragment.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/view/order/OrderFailureActivity.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/view/order/OrderItem.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/view/order/OrderItemAdapter.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/viewmodel/MedicineViewModel.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/viewmodel/OrderViewModel.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/viewmodel/UserViewModel.kt
  FE/app/src/main/java/com/wonchihyeon/ytt_android/viewmodel/VendingMachineViewModel.kt
  FE/app/src/main/res/layout/activity_login.xml
  FE/app/src/main/res/layout/activity_order.xml
  FE/app/src/main/res/layout/activity_order_failure.xml
  FE/app/src/main/res/layout/activity_orderlist.xml
  FE/app/src/main/res/layout/fragment_my.xml
  FE/app/src/main/res/layout/fragment_order.xml
  FE/app/src/main/res/navigation/main_nav.xml
Labels: REFACTOR 🛠️

#34 [FEAT] 약 entity 생성
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Ingredient.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Medicine.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/MedicineIngredient.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Pharmacopeia.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Unit.java
  BE/ytt/src/main/java/com/example/ytt/domain/model/Address.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/domain/VendingMachine.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/dto/VendingMachineDetailDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/dto/VendingMachineDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/service/VendingMachineFindService.java
  BE/ytt/src/test/java/com/example/ytt/domain/medicine/domain/IngredientTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/medicine/domain/MedicineTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/model/AddressTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/vendingmachine/domain/VendingMachineTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/vendingmachine/repository/VendingMachineRepositoryTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/vendingmachine/service/VendingMachineFindServiceTest.java
Labels: FEAT ✨

#47 [FEAT] 약 조회 로직 생성
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Ingredient.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Medicine.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/MedicineIngredient.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/IngredientDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDetailDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/repository/IngredientRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/repository/MedicineIngredientRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/repository/MedicineRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/service/MedicineFindService.java
  BE/ytt/src/main/java/com/example/ytt/global/common/response/ResponseDto.java
  BE/ytt/src/test/java/com/example/ytt/domain/medicine/domain/IngredientTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/medicine/domain/MedicineTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/medicine/repository/MedicineRepositoryTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/medicine/service/MedicineFindServiceTest.java
Labels: FEAT ✨

#52 [FEAT] 약 공공데이터 open api 연결
  BE/ytt/build.gradle
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/controller/MedicineController.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Ingredient.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Medicine.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/MedicineIngredient.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Unit.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/IngredientDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDetailDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineRequestDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/repository/IngredientRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/service/MedicineRegisterService.java
  BE/ytt/src/main/java/com/example/ytt/global/common/respnse/ResponseDto.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SwaggerConfig.java
  BE/ytt/src/main/resources/application.yml
Labels: FEAT ✨

#56 [SETUP] 백엔드 CI/CD 설정
  .github/workflows/backend_cicd.yml
  BE/ytt/build.gradle
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/domain/Medicine.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDetailDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/service/MedicineRegisterService.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/controller/VendingMachineController.java
  BE/ytt/src/main/java/com/example/ytt/global/common/response/ResponseDto.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SecurityConfig.java
Labels: SETUP ⚙️

#57 [FIX] backend cicd 수정
  .github/workflows/backend_cicd.yml
Labels: BUG 🐞

#58 [FIX] 테스트 코드 호출 에러 수정
  BE/ytt/src/test/java/com/example/ytt/domain/medicine/domain/MedicineTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/medicine/repository/MedicineRepositoryTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/medicine/service/MedicineFindServiceTest.java
Labels: BUG 🐞

#64 [REFACTOR] 유저 회원가입,로그인,JWT 리팩토링
  BE/ytt/src/main/java/com/example/ytt/domain/user/auth/jwt/JWTFilter.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/auth/jwt/JWTUtil.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/auth/security/CustomUserDetails.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/auth/security/LoginSuccessHandler.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/controller/AuthController.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/controller/UserController.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/domain/JwtRefresh.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/domain/RefreshEntity.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/domain/User.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/dto/SignUpDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/dto/UpdatePasswordDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/dto/UserDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/exception/ExceptionAdvice.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/exception/UserExceptionType.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/repository/RefreshRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/service/AuthService.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/service/UserService.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SecurityConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SwaggerConfig.java
Labels: REFACTOR 🛠️
