Repository marso34/ytt-medicine-vending-machine, pull requests merged in 2024-12, with the labels that each got.

#103 [FEAT] 주문 동시성 제어 : BE
  .github/workflows/backend_cicd.yml
  BE/ytt/src/main/java/com/example/ytt/domain/favorite/controller/FavoriteController.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/domain/Inventory.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InventoryRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InventoryRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/repository/InventoryRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/inventory/service/InventoryService.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/dto/MedicineDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/repository/MedicineRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/repository/MedicineRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/medicine/service/MedicineFindService.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/controller/OrderController.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/controller/OrderMachineController.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/controller/OrderWebSocketController.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/domain/Order.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/domain/OrderItem.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/domain/OrderState.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderDetailDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderDetailReqDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderItemDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/OrderStoreResDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/machine/OrderResultDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/machine/OrderVendingMachineDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/request/OrderItemReqDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/dto/request/OrderReqDto.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/repository/OrderDetailRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/repository/OrderRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/repository/OrderRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/repository/OrderRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderDetailService.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderFindService.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderManageService.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderService.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/util/UUIDutil.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/service/UserService.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/domain/MachineState.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/service/VendingMachineFindService.java
  BE/ytt/src/main/java/com/example/ytt/global/config/SecurityConfig.java
  BE/ytt/src/main/java/com/example/ytt/global/error/code/ExceptionType.java
  BE/ytt/src/test/java/com/example/ytt/domain/order/service/OrderManageServiceTest.java
  BE/ytt/src/test/java/com/example/ytt/domain/order/service/OrderServiceTest.java
Labels: FEAT ✨, REFACTOR 🛠️

#105 [FEAT] 기간 만료된 RefreshToken 삭제 : BE
  BE/ytt/src/main/java/com/example/ytt/YttApplication.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/repository/RefreshRepository.java
  BE/ytt/src/main/java/com/example/ytt/domain/user/service/AuthService.java
Labels: FEAT ✨

#107 [FIX] 마이페이지 조회 시 userId 누락 부분 수정 #106
  BE/ytt/src/main/java/com/example/ytt/domain/user/service/UserService.java
Labels: BUG 🐞

#108 [REFACTOR] 주문 동시성 제어 수정 : BE
  BE/ytt/src/main/java/com/example/ytt/domain/management/repository/ManagementRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/management/repository/ManagementRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/management/service/ManagementService.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/domain/Order.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/repository/OrderRepositoryCustom.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/repository/OrderRepositoryImpl.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderManageService.java
  BE/ytt/src/main/java/com/example/ytt/domain/vendingmachine/controller/VendingMachineManageController.java
Labels: REFACTOR 🛠️

#109 [FEAT] 특정 자판기의 모든 주문 취소 : BE
  BE/ytt/src/main/java/com/example/ytt/domain/order/controller/OrderController.java
  BE/ytt/src/main/java/com/example/ytt/domain/order/service/OrderManageService.java
Labels: FEAT ✨

#116 [DOCS] ES 문서화 : ES
  ES/README.md
Labels: DOCS 📝

#117 [FEAT] ES 최종 파일 업로드 : ES
  ES/index.html
  ES/order/app.py
  ES/order/cam.py
  ES/order/db.txt
  ES/order/moter/moter.txt
  ES/order/moter/play_check.py
  ES/order/moter/print/step_m1.py
  ES/order/moter/print/step_m2.py
  ES/order/moter/print/step_m3.py
  ES/order/moter/print/step_m4.py
  ES/order/moter/storage_in/1_close.py
  ES/order/moter/storage_in/1_open.py
  ES/order/moter/storage_in/2_close.py
  ES/order/moter/storage_in/2_open.py
  ES/order/moter/storage_in/3_close.py
  ES/order/moter/storage_in/3_open.py
  ES/order/moter/storage_in/4_close.py
  ES/order/moter/storage_in/4_open.py
  ES/order/moter/storage_out/1_out.py
  ES/order/moter/storage_out/2_out.py
  ES/order/moter/storage_out/3_out.py
  ES/order/moter/storage_out/4_out.py
  ES/order/order.html
  ES/order/play.py
  ES/order/specific_task.py
Labels: FEAT ✨

#120 [DOCS] 개발 문서화
  LICENSE.md
  README.md
Labels: DOCS 📝
